# -*- coding: utf-8 -*-
"""Diogo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Zn3z2yfTBsMQmxWA_lCiOAXda-tr5WWH
"""

import numpy as np
import pandas as pd
import scikitlearn
import psycopg2
import sqlalchemy